### ISSUE TITLE
pick and place dataset

### ISSUE THREAD

**Issue by robotlearning123** [hyperplane-lab/RLAfford#4]
Hi, thank you for the great project. It seems that I cannot run the pick and place demo coz no related files in the dataset, like
"dataset/pap_data/object2pick_2/". Could you please help me with this? Thank you very much.

**Comment by GengYiran** [comment]
Thank you for your interest in our work. Since the pick and place, open pot and push stapler dataset comes from 3 different original datasets, including Part-Mobility Dataset, OmniHang Dataset and VAPO dataset, etc., we are recently seeking permission from the authors concerned and will sort out the code once they agree. However, for your convenience, I will use a small dataset in the near future to make sure the code is ready to run.

**Comment by robotlearning123** [comment]
That is great! Thank you.

**Comment by JackMa-coder** [comment]
Hello, I have encountered the same problem.  Like @wangcongrobot ,I cannot run the pick and place demo coz no related files in the dataset, like"dataset/pap_data/object2pick_2/" Do you have any solutions now? 
Thank you for any help.

**Comment by boshi-an** [comment]
@GengYiran Is the permission granted?

**Comment by GengYiran** [comment]
Yes, I've already sent the datasets to @wangcongrobot  through email. The download link is here: https://drive.google.com/file/d/11G3r2mvAUzzetg_0APJd-eSMbprrMAvW/view?usp=sharing, Notice that you should do some convex decomposition to accelerate training~

**Comment by Anonymous-ICRA2026** [comment]
Hi,
Thanks for sharing! It looks like the Google Drive link (https://drive.google.com/file/d/11G3r3mvAUzzetg_0APJd-eSMbprrMAvW/view?usp=sharing) is no longer working—could you please refresh or resend it? 
Thank you for any help.

**Comment by boshi-an** [comment]
Yes, will do that! After it’s done I will post here
