### ISSUE TITLE
Bug with door index?

### ISSUE THREAD

**Issue by Xingyu-Lin** [hyperplane-lab/RLAfford#8]
https://github.com/hyperplane-lab/RLAfford/blob/a0e650eeb79e2b62395e787b9ff131118109903e/MARL_Module/envs/tasks/franka_cabinet.py#LL144C21-L144C21

This line finds the cabinet index based on the first environment. However, `self.cabinet_rig_name` varies across environments. Is this a bug? I have met situations where index returns -1

**Comment by Xingyu-Lin** [comment]
Tentatively solves the issue by changing [this line](https://github.com/hyperplane-lab/RLAfford/blob/a0e650eeb79e2b62395e787b9ff131118109903e/MARL_Module/envs/tasks/franka_cabinet.py#LL445C31-L445C34) to 
```
                if id == 0:
                    self.cabinet_rig_name = list(rig_dict.keys())[1]
```
But maybe the author can provide more explanation and suggest better solution

**Comment by Xingyu-Lin** [comment]
I also wonder how much this changes the whole benchmark? Seems like this function is closely related to the reward function, which affects both training and evaluation metric

**Comment by boshi-an** [comment]
We have modified the dataset so that all modles only have 2 rigid bodies, one is fixed with the base, one is the moving part. We believe 1 will always be index of the moving part. Concerning how you had situations where index returns -1, we would like to further investigate this issue. Could you provide the case how the index returns -1?
